version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER} -d expense_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=proxyOFF
      - SQL_USER=${SQL_USER}
      - SQL_PASS=${SQL_PASS}
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data: