telegram:
  bot:
    whitelist:
      enabled: true
      admin-ids: ${ADMIN_IDS}
    token: ${BOT_TOKEN}
    name: ${BOT_NAME}
    proxy:
      host: ${HOST}
      port: ${PORT}
      type: ${TYPE}
      username: ${USERNAME}
      password: ${PASSWORD}